### Funções do Programa Principal

In [1]:
def exibir_matriz(matriz): 
    for linha in matriz:
        print(linha) 
    return ''
def soma_matrix (A, B):
    C = []
    nLinhasA, nLinhasB = len(A), len(B)
    nColA, nColB = len(A[0]), len(B[0])
    
    if (nLinhasA == nLinhasB) and (nColA == nColB):
        for i in range(nLinhasA):
            linha = [0]*nColA
            C.append(linha)
            for j in range(nColA):
                C[i][j] = A[i][j] + B[i][j]       
    else:
        print('Matrizes não tem a mesma ordem')    
    return C
def oposta(M):
    op = []
    for i in range(len(M)):
        linha =[0]*len(M[0])
        op.append(linha)
        for j in range(len(M[0])):
            op[i][j] = -M[i][j]
    return op
def subtrair(A, B):
    return soma_matrix(A, oposta(B))    

### Álgebra Linear
### Lista de Exercícios

In [2]:
import numpy as np
import pandas as pd

### 1º) Sejam as matrizes:
### A=[[1, 2, 3], [2, 1, 4]; B=[1, 0], [2, 1], [3, 2]]; C=[[3, -1, 3], [4, 1, 5], [2, 1, 3]]; D= [[3, -2], [2, 4]];
### E=[[2, -4, 5], [0, 1, 4], [3, 2, 1]]; F= [[-4, 5], [2,3]] e O=[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
### Se possível, Calcule:
### a) 𝐶 + 𝐸 // b) 3𝐷 + 2𝐹 // c) 𝐴𝑇 // d) 𝐷 − 𝐷𝑇 // e) −3𝐶 + 5𝑂

In [11]:
#a = [[1, 2, 3], [2, 1, 4]]
#b = [[1, 0], [2, 1], [3, 2]]
#c = [[3, -1, 3], [4, 1, 5], [2, 1, 3]]
#d = [[3, -2], [2, 4]]
#e = [[2, -4, 5], [0, 1, 4], [3, 2, 1]]
#f = [[-4, 5], [2,3]]
#o = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
exibir_matriz(soma_matrix(c, e))
print('a) Resultado da soma da matriz C e E\n')
#print(exibir_matriz(d))
#print(exibir_matriz(f))
#d1 = np.dot(d, d)
#print(exibir_matriz(d1))
#d2 = np.dot(d1, d)
#print(exibir_matriz(d2))
#f1 = np.dot(f, f)
#print(exibir_matriz(f1))
df = soma_matrix(d2, f1)
print('b)', exibir_matriz(df),'Resultado da soma das matrizes 3D + 2F\n')
#print('Matriz A\n', exibir_matriz(a))
#at = np.transpose(a)
#print('c)', exibir_matriz(at),'Transposta da matriz A\n')
#print('Matriz D\n', exibir_matriz(d))
#dt = np.transpose(d)
#print('Tranposta da matriz D\n', exibir_matriz(dt))
#sub = subtrair(d, dt)
print('d) Resultado da subtração da matriz D e Dt\n', exibir_matriz(sub))
#print(exibir_matriz(c))
#print(exibir_matriz(o))
#c2 = np.dot(c, c)
#c3 = np.dot(c2, c)
#print(exibir_matriz(c3))
print(exibir_matriz(soma_matrix(c3, o)), 'e) Resultado da Matrizes -3C + 5O')

[5, -5, 8]
[4, 2, 9]
[5, 3, 4]
a) Resultado da soma da matriz C e E

[13, -71]
[64, 39]
b)  Resultado da soma das matrizes 3D + 2F

[0, -4]
[4, 0]
d) Resultado da subtração da matriz D e Dt
 
[55, 1, 67]
[150, 8, 184]
[96, 6, 118]
 e) Resultado da Matrizes -3C + 5O


### 2º) Determine o total de custos de produção e transporte.
### F1 = [[32, 40], [50, 80], [70, 20]] e F2 = [[40, 60], [50, 50], [130, 20]]

In [ ]:
f1 = [[32, 40], [50, 80], [70, 20]]
f2 = [[40, 60], [50, 50], [130, 20]]
f3 = soma_matrix(f1, f2)
print(exibir_matriz(f3),'Resultado da soma das matrizes F1 e F2')

###  3º) Sejam as Matrizes:
### A=[[1, 2, -3], [4, 0, -2]; B=[[3, 1], [2, 4], [-1, 5]]; C=[[2, 3, 1], [3, -4, 5], [1, -1, -2]]; D=[[2, 3], [-1. -2]]
### Se possível, calcule:

In [13]:
z = [[1, 2, -3], [4, 0, -2]]
y = [[3, 1], [2, 4], [-1, 5]]
x = [[2, 3, 1], [3, -4, 5], [1, -1, -2]]
w = [[2, 3], [-1, -2]]

#print(exibir_matriz(z))
#print(exibir_matriz(y))
#print(exibir_matriz(x))
#print(exibir_matriz(w))

zy = np.dot(z, y)
yz = np.dot(y, z)
xy = np.dot(x, y)
yw = np.dot(y, w)
zyw = np.dot(z, yw)
wyz = np.dot(zy, w)
xyw = soma_matrix(xy, w)

print('a)',exibir_matriz(zy),'Resultado da matriz AB\n')
print('b)',exibir_matriz(yz),'Resultado da matriz BA\n')
print('c)',exibir_matriz(xyw),'CB + D - Matrizes não tem a mesma ordem\n')
#print(exibir_matriz(yw), 'Resultado da matriz BD\n')
print('d)',exibir_matriz(zyw),'Resultado da matriz A(BD)\n')
print('e)',exibir_matriz(wyz),'Resultado da matriz (AB)D\n')

Matrizes não tem a mesma ordem
[10 -6]
[14 -6]
a)  Resultado da matriz AB

[  7   6 -11]
[ 18   4 -14]
[19 -2 -7]
b)  Resultado da matriz BA

c)  CB + D - Matrizes não tem a mesma ordem

[26 42]
[34 54]
d)  Resultado da matriz A(BD)

[26 42]
[34 54]
e)  Resultado da matriz (AB)D



### 4ª) Se I2 = [[1, 0], [0, 1]] e D = [[2, 3], [-1, -2]]
### Calcule I2 D e D I2

In [15]:
i2 = [[1, 0], [0, 1]]
v = [[2, 3], [-1, -2]]

i2v = np.dot(i2, v)
v = np.dot(v, i2)


print(exibir_matriz(i2v),'O resultado da multiplicação das matrizes I2 D')
print(exibir_matriz(v),'O resultado da multiplicação das matrizes D I2')

[2 3]
[-1 -2]
 O resultado da multiplicação das matrizes I2 D
[2 3]
[-1 -2]
 O resultado da multiplicação das matrizes D I2


### 5º) Seja 𝒑 = [𝟏𝟖, 𝟗𝟓 𝟏𝟒, 𝟕𝟓 𝟖, 𝟔] um vetor de
### dimensão 3 que representa os preços atuais de três itens de uma loja.
### Suponha que a loja anuncie uma promoção em que o preço de cada item
### esteja reduzido em 20%.
### a) Determine um vetor de dimensão 3 que forneça as alterações de preço  para os três itens.
### b) Determine um vetor de dimensão 3 que forneça os novos preços dos itens.

In [17]:
a#a) 
p = [[18.95, 14.75, 8,6]]  # a)[3.79, 2.95, 1.72] // b) [15.16, 11.8, 6.88]
print(exibir_matriz(p))

[18.95, 14.75, 8, 6]



### 6º) A Matriz [[3, 0], [0, 2]] é uma combinação linear das matrizes [[1, 0], [0, 1]] e [[1,0], [0; 0]]?

In [ ]:
m1 = exibir_matriz([[3, 0], [0, 2]])
m2 = exibir_matriz([[1, 0], [0, 1]])
m3 = exibir_matriz([[1, 0], [0, 0]])

### 7º) Encontre a quantidade de pesticida do tipo i que o animal j absorveu.

In [32]:
pl = [[2, 3, 4, 3], [3, 2, 2, 5], [4, 1, 6, 4]]
herb = [[20, 12, 8], [28, 15, 15], [30, 12, 10], [40, 16, 20]]
print(exibir_matriz(pl))
print(exibir_matriz(herb))
prod = np.dot(pl, herb)
print(prod)

[2, 3, 4, 3]
[3, 2, 2, 5]
[4, 1, 6, 4]

[20, 12, 8]
[28, 15, 15]
[30, 12, 10]
[40, 16, 20]

[[364 165 161]
 [376 170 174]
 [448 199 187]]
